### ISSUE TITLE
请检查

### ISSUE THREAD

**Issue by k0sf** [MiSecurity/x-patrol#13]
```
[0000] PANIC xsec patrol: Error 1045: Access denied for user 'root'@'localhost' (using password: YES)
panic: (*logrus.Entry) (0xab5420,0xc420196050)

goroutine 1 [running]:
github.com/sirupsen/logrus.Entry.log(0xc420088280, 0xc420083320, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/yang/gocode/src/github.com/sirupsen/logrus/entry.go:112 +0x254
github.com/sirupsen/logrus.(*Entry).Panic(0xc420088370, 0xc420175bd0, 0x1, 0x1)
	/home/yang/gocode/src/github.com/sirupsen/logrus/entry.go:182 +0xaa
github.com/sirupsen/logrus.(*Entry).Panicln(0xc420088370, 0xc420175cc0, 0x1, 0x1)
	/home/yang/gocode/src/github.com/sirupsen/logrus/entry.go:277 +0xd5
x-patrol/models.init.0()
	/home/yang/gocode/src/x-patrol/models/models.go:70 +0x415
exit status 2

```

**Comment by netxfly** [comment]
看输出提示是数据库密码不对，可以手工先用mysql 客户端连接一下确认下能否连接。
