### ISSUE TITLE
求助如何解决，感谢

### ISSUE THREAD

**Issue by Baibing0118** [MiSecurity/x-patrol#38]
./x-patrol_darwin_amd64 scan
[0000]  INFO xsec patrol: scan github code
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x15a5a9a]

goroutine 18 [running]:
x-patrol/util/githubsearch.(*Client).SearchCode(0xc000257d60, 0xc000274760, 0x16, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/lbb/go/src/x-patrol/util/githubsearch/gitclient.go:158 +0x32a
x-patrol/util/githubsearch.Search.func1(0xc000270fa0, 0xc000257d60, 0x17, 0xc000270f28, 0x6, 0xc000270f48, 0x5, 0xc000274760, 0x16, 0xc000270f70, ...)
	/Users/lbb/go/src/x-patrol/util/githubsearch/search.go:67 +0x6f
created by x-patrol/util/githubsearch.Search
	/Users/lbb/go/src/x-patrol/util/githubsearch/search.go:65 +0x168

**Comment by simple0313** [comment]
我也遇到这个问题了 请问如何解决的啊
